CREATE TABLE CLIENTE(
ID_CLIENTE NUMERIC(11) UNIQUE NOT NULL,
NOME TEXT NOT NULL,
QUANTIDADE_PEDIDOS NUMERIC(3) NOT NULL,
VALOR_PAGAMENTO NUMERIC(5, 2), --99999,99
PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE CONTATO(
ID_CONTATO numeric(11) NOT NULL,
ID_CLIENTE numeric(11) NOT NULL,
TELEFONE varchar(14) NOT NULL,
DESCRICAO text NOT NULL,
CONSTRAINT PK_CONTATO_ID_CONTATO PRIMARY KEY (ID_CONTATO, ID_CLIENTE),
CONSTRAINT FK_CONTATO_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE ENDERECO(
ID_ENDERECO numeric(11) NOT NULL,
ID_CLIENTE numeric(11) NOT NULL,
LOGRADOURO text NOT NULL,
NUMERO numeric(8) NOT NULL,
CEP CHAR(9) NOT NULL,
CIDADE text NOT NULL,
BAIRRO text NOT NULL,
COMPLEMENTO text NOT NULL,
CONSTRAINT PK_ENDERECO_ID_ENDERECO PRIMARY KEY (ID_ENDERECO, ID_CLIENTE),
CONSTRAINT FK_ENDERECO_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE ANIMAL(
ID_ANIMAL numeric(11) NOT NULL,
ID_CLIENTE numeric(11) NOT NULL,
NOME text NOT NULL,
TIPO text NOT NULL,
RACA text NOT NULL,
PELAGEM numeric(1) NOT NULL,
PORTE numeric(1) NOT NULL,
IDADE numeric(3), 
CONSTRAINT PK_ANIMAL_ID_ANIMAL PRIMARY KEY (ID_ANIMAL, ID_CLIENTE),
CONSTRAINT FK_ANIMAL_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE PEDIDO(
ID_PEDIDO numeric(11) NOT NULL,
ID_CLIENTE numeric (11) NOT NULL,
ID_ANIMAL numeric(11) NOT NULL,
SERVICO text NOT NULL,
VALOR numeric(5, 2) NOT NULL,
DESCRICAO text not null,
STATUS text not null,
DATA_E_HORA_GERADA timestamp,
CONSTRAINT PK_PEDIDO_ID_PEDIDO PRIMARY KEY (ID_PEDIDO),
CONSTRAINT FK_PEDIDO_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
CONSTRAINT FK_PEDIDO_ID_ANIMAL FOREIGN KEY (ID_ANIMAL, ID_CLIENTE) REFERENCES ANIMAL(ID_ANIMAL, ID_CLIENTE)
);

create sequence SEQ_ID_CLIENTE
increment 1
start 1;

create sequence SEQ_ID_CONTATO
increment 1
start 1;

create sequence SEQ_ID_ENDERECO
increment 1
start 1;

create sequence SEQ_ID_ANIMAL
increment 1
start 1;

create sequence SEQ_ID_PEDIDO
increment 1
start 1;